// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojfdhkwgpmisdkmelndf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZmRoa3dncG1pc2RrbWVsbmRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTI2NDQsImV4cCI6MjA2NTc2ODY0NH0.EAiI6yc8MYK5f7YG9tBvppy94rV8T-Z8OgCeGo_i_Sw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);